# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
#  config.vm.network "public_network"
  config.vm.network "private_network", auto_config: false, ip: "192.168.0.10"
  config.vm.synced_folder "playbooks/", "/vagrant/playbooks"

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

###
###
  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.box = "generic/fedora36"
  # Static ip configuration for fedora 36 is not working see:
  # https://github.com/hashicorp/vagrant/issues/12762
  # Workaroung use vm.provision with shell or Ansible playbooks for configuring the static ip
  # haproxy.vm.provision "shell",
  #  run: "always",
  #  inline: "ifconfig eth1 192.168.0.10 netmask 255.255.255.0 up"
    haproxy.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/vagrant/playbooks/haproxy.yml"
    end
  end
####
####
  config.vm.define "consul" do |consul|
    consul.vm.box = "generic/fedora36"
    consul.vm.network "forwarded_port", guest: 8500, host: 8500
    consul.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/vagrant/playbooks/consul.yml"
    end
  end
####
####
  config.vm.define "backend" do |backend|
    backend.vm.box = "generic/fedora36"
  # Static ip configuration for fedora 36 is not working see:
  # https://github.com/hashicorp/vagrant/issues/12762
  # Workaroung use vm.provision with shell or Ansible playbooks for configuring the static ip
     backend.vm.provision "ansible_local" do |ansible|
       ansible.playbook = "/vagrant/playbooks/backend.yml"
    end
  end
###
###
end
