---
- hosts: all
  become: yes
  tasks:
    - set_fact:
        random_ip: "{{ 100 | random }}" # not some random :D
      run_once: yes

    - name: Add an Ethernet connection with static IP configuration
      nmcli:
        conn_name: eth1
        ifname: eth1
        type: ethernet
        ip4: 192.168.0.{{ random_ip }}/24
        gw4: 192.168.0.1
        state: present

    - name: Add Hashicorp repository
      yum_repository:
        name: hashicorp
        description: Hashicorp repository
        baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://rpm.releases.hashicorp.com/gpg

          
    - name: Install the latest version of the Consul
      yum: 
        name: consul
        state: latest

    - name: Configuring Consul agent
      copy:
        src: /vagrant/playbooks/files/consul-agent.service
        dest: /usr/lib/systemd/system/consul.service
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Enable consul service
      systemd:
        name: consul
        daemon_reload: yes
        enabled: yes

    - name: Start consul
      systemd:
        name: consul
        state: started

    ## TODO: Replace this task with a .hcl configuration, and let the app name as a parameter so we can register more than app
    ## Probably have a ansible role just for registering the apps
    - name: Registering the service for the app.
      shell:  consul services register -name demo-app-{{ random_ip }} -address 192.168.0.{{ random_ip }}

    ## Call the api/cli and check if service was registered
    ## consul catalog services
