---
- hosts: all
  become: yes
  tasks:

    - name: Add an Ethernet connection with static IP configuration
      nmcli:
        conn_name: eth1
        ifname: eth1
        type: ethernet
        ip4: 192.168.0.11/24
        gw4: 192.168.0.1
        state: present

    - name: Add Hashicorp repository
      yum_repository:
        name: hashicorp
        description: Hashicorp repository
        baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://rpm.releases.hashicorp.com/gpg

          
    - name: Install the latest version of the Consul
      yum: 
        name: consul
        state: latest

    - name: Configuring Consul on dev mode
      copy:
        src: /vagrant/playbooks/files/consul.service
        dest: /usr/lib/systemd/system/consul.service
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Allow traffic towards Consul server
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
         - "8301/tcp"
         - "8500/tcp"
         - "8600/tcp"
         - "53/tcp"
         - "53/udp"

    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded

    - name: Enable service HAProxy
      systemd:
        name: consul
        daemon_reload: yes
        enabled: yes

    - name: Start consul
      systemd:
        name: consul
        state: started
