---
- hosts: all
  become: yes
  tasks:
    - name: Install the latest version of the HAProxy
      yum: 
        name: haproxy 
        state: latest

    - name: Add an Ethernet connection with static IP configuration
      nmcli:
        conn_name: eth1
        ifname: eth1
        type: ethernet
        ip4: 192.168.0.10/24
        gw4: 192.168.0.1
        state: present

    - name: Copy haproxy config
      copy:
        src: /vagrant/playbooks/files/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Enable service HAProxy
      systemd:
        name: haproxy
        enabled: yes

 # TODO: Add specificy port to selinux
    - name: Set haproxy_connect_any flag on and keep it persistent across reboots
      seboolean:
        name: haproxy_connect_any
        state: yes
        persistent: yes

    - name: Start HAProxy
      systemd:
        name: haproxy
        state: started

